// Code generated by "jade.go"; DO NOT EDIT.

package main

import (
	"bytes"
	"io"
	"fmt"
	"html"
	"strconv"
	"github.com/Joker/hpp"
	pool "github.com/valyala/bytebufferpool"
)

func Jade_footer(wr io.Writer) {
	buffer := &WriterAsBuffer{wr}

	buffer.WriteString(`<div class="footer">2019</div>`)

}
