// Code generated by "jade.go"; DO NOT EDIT.

package main

import (
	"io"
)

func Jade_footer(wr io.Writer) {
	buffer := &WriterAsBuffer{wr}

	buffer.WriteString(`<div class="footer">2019</div>`)

}
