// Code generated by "jade.go"; DO NOT EDIT.

package main

import (
	"bytes"
	"io"
	"fmt"
	"html"
	"strconv"
	"github.com/Joker/hpp"
	pool "github.com/valyala/bytebufferpool"
)

func Index(pageTitle string, youAreUsingJade bool, wr io.Writer) {
	buffer := &WriterAsBuffer{wr}

	buffer.WriteString(`<!DOCTYPE html><html lang="en"><head><title>`)
	WriteEscString(pageTitle, buffer)
	buffer.WriteString(`</title><script type="text/javascript">			if(question){
				answer(40 + 2)
			}</script></head><body><h1>Jade - template engine`)

	{
		var (
			golang = "Go"
		)

		buffer.WriteString(`<div id="cmd">Precompile jade templates to `)
		WriteEscString(golang, buffer)
		buffer.WriteString(` code.</div>`)
	}

	buffer.WriteString(`</h1><div id="container" class="col">`)

	if youAreUsingJade {
		buffer.WriteString(`<p>You are amazing</p>`)

	} else {
		buffer.WriteString(`<p>Get on it!</p>`)

	}
	buffer.WriteString(`<p>				Jade/Pug is a terse and simple
				templating language with
				a <strong>focus</strong> on performance 
				and powerful features.</p></div><footer><div class="footer">2019</div><span>twoj stary</span></footer></body></html>`)

}
